models.py
from flask_login import UserMixin
from app import db


class User(UserMixin, db.Model):
    __tablename__ = 'user'
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(100), unique=True)
    email = db.Column(db.String(100), unique=True)
    password = db.Column(db.String(100))
    tasks = db.relationship('Task', backref='owner')

    def __repr__(self):
        return '<User {}>'.format(self.username)


class Task(db.Model):
    __tablename__ = 'task'
    id = db.Column(db.Integer, primary_key=True)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    type = db.Column(db.String(100))
    description = db.Column(db.String(100))
    status = db.Column(db.String(100))

    def __repr__(self):
        return '<Task {}>'.format(self.description)

forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, validators


class RegistrationForm(FlaskForm):
    username = StringField('Username', [validators.Length(min=4, max=25)])
    email = StringField('Email', [validators.Email(message='Invalid email format.')])
    password = PasswordField('Password', [
        validators.DataRequired(),
        validators.EqualTo('confirm', message='Passwords must match.')])
    confirm = PasswordField('Confirm Password.')


class LoginForm(FlaskForm):
    username = StringField('Username', [validators.Length(min=4, max=25)])
    password = PasswordField('Password', [validators.DataRequired()])

__init__.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

# Instantiate SQL_Alchemy DB
db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')

    db.init_app(app)

    # Instantiate Login Manager to help with authentication
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # Import user model for user querying
    from models import User

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    # Import and register blueprints for routing
    from views import auth, main
    app.register_blueprint(auth)
    app.register_blueprint(main)

    return app

app.py
from flask import Flask
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy

# Instantiate SQL_Alchemy DB
db = SQLAlchemy()


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')

    db.init_app(app)

    # Instantiate Login Manager to help with authentication
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    # Import user model for user querying
    from models import User

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))

    # Import and register blueprints for routing
    from views import auth, main, tasks
    app.register_blueprint(auth)
    app.register_blueprint(main)
    app.register_blueprint(tasks)

    return app


if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

views/__init__.py
from .auth import auth
from .main import main
from .tasks import tasks

views/auth.py
from app import db
from time import sleep
from models import User
from forms import RegistrationForm, LoginForm
from flask_login import current_user, login_required, login_user, logout_user
from flask import Blueprint, flash, render_template, redirect, request, url_for
from werkzeug.security import generate_password_hash, check_password_hash

auth = Blueprint('auth', __name__)


@auth.route('/login', methods=['GET'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = LoginForm(request.form)
    return render_template('login.html', form=form)


@auth.route('/login', methods=['POST'])
def login_post():
    form = LoginForm(request.form)
    user = User.query.filter_by(username=form.username.data).first()

    if not user and not check_password_hash(user.password, form.password.data):
        flash('Please check your login credentials and try again')
        return redirect(url_for('auth.login'))

    login_user(user)

    return redirect(url_for('main.index'))


@auth.route('/register', methods=['GET'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))
    form = RegistrationForm(request.form)
    return render_template('register.html', form=form)


@auth.route('/register', methods=['POST'])
def register_post():
    form = RegistrationForm(request.form)
    if form.validate():
        username = form.username.data
        user = User.query.filter_by(username=username).first()
        if user:
            flash('User already exits!')
            sleep(2)
            return redirect(url_for('auth.login'))

        user = User(username=form.username.data, email=form.email.data,
                    password=generate_password_hash(form.password.data, method='sha256'))
        db.session.add(user)
        db.session.commit()
        return redirect(url_for('auth.login'))

    return render_template('register.html', form=form)


@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

views/main.py
from flask import Blueprint, flash, render_template, redirect, request, url_for
from flask_login import current_user

main = Blueprint('main', __name__)


@main.route('/', methods=['GET'])
def index():
    return render_template('index.html', user=current_user)

views/tasks.py
from app import db
from models import Task
from flask import Blueprint, flash, render_template, redirect, request, url_for
from flask_login import login_required, current_user

tasks = Blueprint('tasks', __name__)


@tasks.route('/tasks', methods=['GET'])
@login_required
def get_all_tasks():
    user_id = current_user.id
    tasks_list = Task.query.filter_by(user_id=user_id).all()

    tasks_list = [x for x in tasks_list if x.status != 'closed']

    return render_template('tasks.html', tasks_list=tasks_list, user=current_user)


@tasks.route('/tasks', methods=['POST'])
@login_required
def create_task():
    user_id = current_user.id
    type = request.form.get('type')
    description = request.form.get('description')
    status = 'OPEN'

    task = Task(user_id=user_id, type=type, description=description, status=status)

    db.session.add(task)
    db.session.commit()


@tasks.route('/tasks/<int:identifier>', methods=['DELETE'])
@login_required
def remove_task(identifier):
    task = Task.query.filter_by(id=identifier).first()

    if not task:
        flash('There is no task associated with that id.')
        return redirect(url_for('tasks.tasks'))

    Task.query.filter_by(id=task.id).delete()
    db.session.commit()

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.2/css/bulma.min.css">
    <link rel="stylesheet" href="{{url_for('static', filename='main.css')}}">
    <title>Tracky</title>
</head>
<body>
<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-menu">
        <div class="navbar-end">
            <a class="navbar-item" href={{url_for('main.index') }}> Home </a>
            <a class="navbar-item" href={{url_for('tasks.get_all_tasks') }}>Tasks </a>
            <a class="navbar-item" href={{url_for('auth.logout') }}> Logout </a>
        </div>
    </div>
</nav>
<div class="content">
    {% block content %}
    {% endblock %}
</div>
</body>
</html>

templates/home.html
{% extends "base.html" %}
{% block content %}


{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block content %}
<div class="container">
    <h3>Home</h3>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }}
        </div>
        {% endif %}
        {% endwith %}
        <form method="POST" action="/login">
            <h3 class="title" style="text-align: center">Login</h3>
            <div class="field">
                <div class="control">
                    {{form.username(class='input is-large', placeholder='Username')}}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{form.password(class='input is-large', placeholder='Password')}}
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Login</button>
        </form>
    </div>
</div>
{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="column is-4 is-offset-4">
    <div class="box">
        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="notification is-danger">
            {{ messages[0] }} Go to <a href="{{ url_for('auth.login') }}">login page</a>.
        </div>
        {% endif %}
        {% endwith %}
        <h3 class="title" style="text-align: center">Sign Up</h3>
        <form action="/register" method="POST">
            {{ form.csrf_token() }}
            <div class="field">
                <div class="control">
                    {{form.username(class='input is-large', placeholder='Username')}}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{form.email(class='input is-large', placeholder='Email')}}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{form.password(class='input is-large', placeholder='Password')}}
                </div>
            </div>
            <div class="field">
                <div class="control">
                    {{form.confirm(class='input is-large', placeholder='Confirm Password')}}
                </div>
            </div>
            <button class="button is-block is-info is-large is-fullwidth">Register</button>
        </form>
    </div>
</div>
{% endblock %}

templates/tasks.html
{% extends "base.html" %}
{% block content %}

<div class="container">
    <h3>{{user.username}}'s tasks</h3>
    <table class="table is-bordered is-hoverable is-fullwidth is-narrow is-striped" name="tblList" border=1>
        <tr>
            <th>Task Type</th>
            <th>Description</th>
            <th>Status</th>
        </tr>
        {% for task in tasks_list %}
        <tr>
            <td>{{task.type}}</td>
            <td>{{task.description}}</td>
            <td>{{task.status}}</td>
        </tr>
        {% endfor %}
    </table>
</div>
{% endblock %}